# Generated by Django 5.2.1 on 2025-05-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='core.cita')),
            ],
        ),
    ]
