# Generated by Django 5.2.1 on 2025-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('presentacion', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
